languageCode = 'id'
title = 'Catatan hugo'
theme = 'hugo-theme-relearn'

[goldmark]
[goldmark.renderer]
unsafe = true

[goldmark.parser]
autoHeadingID = true
autoHeadingIDType = "github"
wrap = 100


[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
hardWraps = true

[markup.goldmark.parser]
autoHeadingID = true

[markup.goldmark.parser.attribute]
block = true


[params]
themeVariant = [
    'zen-light',
    'zen-dark',
] # bisa juga "relearn-dark", "zen-light", "zen-dark", dll
# customCSS = ["css/custom.css"] # path relatif ke folder /static/
collapsibleMenu = true
