# Default config
tabWidth: 4
endOfLine: lf
singleQuote: true
printWidth: 100000
trailingComma: none
bracketSameLine: true
quoteProps: consistent
experimentalTernaries: true

plugins: ["prettier-plugin-go-template"]
goTemplateBracketSpacing: true

# Overrided config
overrides:
  - files: ["*.md", "*.json", "*.yaml"]
    options:
      tabWidth: 2
      singleQuote: false
  - files: ["*.html"]
    options:
      parser: "go-template"
      tabWidth: 2
